# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'CoreStructure_iOS' do
  use_frameworks!


 	
  pod 'Firebase/Auth' # Auth create account, log in log out
  pod 'Firebase/Firestore'  # Add this line for Firestore store data in bd
#  pod 'Firebase/Messaging' # push message from fire base
#  pod 'GoogleSignIn'
#  pod 'RealmSwift', '~>10'

end
