# Uncomment the next line to define a global platform for your project
# platform :ios, '13.0'

target 'CoreStructure_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoreStructure_iOS
 	pod 'RealmSwift', '~>10'

end
